name: SlimyTreeTaps
version: ${project.version}
author: TheBusyBiscuit
description: 黏液科技附加 黏液橡膠龍頭 繁體翻譯版.
website: https://github.com/TheBusyBiscuit/SlimyTreeTaps

main: io.github.thebusybiscuit.slimytreetaps.TreeTaps
depend: [Slimefun]

api-version: 1.14